baseURL: "https://wenhan.blog/"
languageCode: en-us
title: Wenhan blog
ignoreLogs: ['warning-goldmark-raw-html']
theme: "PaperMod"
pagination.pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-87273435-2

minify:
  disableXML: true
  minifyOutput: true

params:
  social: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Wenhan blog
  description: "尘归尘，土归土"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: true
  disqusShortname: xibuka

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://media.licdn.com/dms/image/C4D03AQHsFHxbDCgPsA/profile-displayphoto-shrink_400_400/0/1517015003915?e=1683763200&v=beta&t=PR0k2MbOHcJjtozRAQipgSz2CGprYxywDGgXInkOXmo"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Wenhan blog
    subtitle: "Hi there \U0001F44B, Welcome to the dack side"
    imageUrl: "/img/me.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: wenhan
    buttons:
      - name: Posts
        url: post
      - name: Archives
        url: "/archives"
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to the dack side

  Social: 
    twitter: "shi_wenhan"    # Add your Twitter handle without @
  socialIcons:
    - name: email
      url: "mailto:shibunkan@gmail.com"
    - name: twitter
      url: "https://twitter.com/shi_wenhan"
    - name: linkedin
      url: "https://www.linkedin.com/in/wenhan-shi-0883a9132/"
    - name: github
      url: "https://github.com/xibuka"
    - name: zhihu
      url: "https://www.zhihu.com/people/xibuka"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

defaultContentLanguage: ja
defaultContentLanguageInSubdir: true

languages:
  en:
    contentDir: content/post/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
    params:
      subtitle: Hi there \U0001F44B, Welcome to the dack side
    title: Wenhan Blog
    weight: 2

  ja:
    contentDir: content/post/ja
    disabled: false
    languageCode: ja-JP
    languageDirection: ltr
    languageName: 日本語
    params:
      subtitle: Hi there \U0001F44B, Welcome to the dack side
    title: Wenhan Blog
    weight: 1

  zh:
    contentDir: content/post/zh
    disabled: false
    languageCode: zh-CN
    languageDirection: ltr
    languageName: 中文
    params:
      subtitle: \U0001F44B, 今天你学废了吗？
    title: Wenhan Blog
    weight: 3

renderer.unsafe: true